// 省份
export const REGION_PROVINCE = [
  '京',
  '津',
  '沪',
  '渝',
  '苏',
  '浙',
  '豫',
  '粤',
  '川',
  '陕',
  '冀',
  '辽',
  '吉',
  '皖',
  '闽',
  '鄂',
  '湘',
  '鲁',
  '晋',
  '黑',
  '赣',
  '贵',
  '甘',
  '桂',
  '琼',
  '云',
  '青',
  '蒙',
  '藏',
  '宁',
  '新',
];
// 车牌号码的字符
export const PLATE_INPUT_NUMBER = [
  { isLetter: false, value: '0' },
  { isLetter: false, value: '1' },
  { isLetter: false, value: '2' },
  { isLetter: false, value: '3' },
  { isLetter: false, value: '4' },
  { isLetter: false, value: '5' },
  { isLetter: false, value: '6' },
  { isLetter: false, value: '7' },
  { isLetter: false, value: '8' },
  { isLetter: false, value: '9' },
  { isLetter: true, value: 'A' },
  { isLetter: true, value: 'B' },
  { isLetter: true, value: 'C' },
  { isLetter: true, value: 'D' },
  { isLetter: true, value: 'E' },
  { isLetter: true, value: 'F' },
  { isLetter: true, value: 'G' },
  { isLetter: true, value: 'H' },
  { isLetter: true, value: 'J' },
  { isLetter: true, value: 'K' },
  { isLetter: true, value: 'L' },
  { isLetter: true, value: 'M' },
  { isLetter: true, value: 'N' },
  { isLetter: true, value: 'P' },
  { isLetter: true, value: 'Q' },
  { isLetter: true, value: 'R' },
  { isLetter: true, value: 'S' },
  { isLetter: true, value: 'T' },
  { isLetter: true, value: 'U' },
  { isLetter: true, value: 'V' },
  { isLetter: true, value: 'W' },
  { isLetter: true, value: 'X' },
  { isLetter: true, value: 'Y' },
  { isLetter: true, value: 'Z' },
];
